version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: "on-failure"
    networks:
      - nginx_net
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - book_store
      - book_warehouse

  book_store:
    container_name: book_store
    build:
      context: .
      dockerfile: docker/book_store/Dockerfile
    restart: "on-failure"
    volumes:
      - ./book_store/:/usr/app/
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    networks:
      - nginx_net
      - store_net
    expose:
      - "8000"
    env_file:
      - book_store/store.env
    depends_on:
      - store_db

  store_db:
    container_name: store_db
    image: postgres:latest
    restart: "on-failure"
    networks:
      - store_net
    volumes:
      - store_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: store_postgres
      POSTGRES_USER: store_postgres

  redis:
    container_name: store_redis
    image: redis:latest
    networks:
      - store_net
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-alpine
    restart: always
    networks:
      - store_net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: docker/book_store/Dockerfile
    networks:
      - store_net
    volumes:
      - ./book_store/:/usr/app/
    command: celery -A book_store worker -l INFO
    env_file:
      - book_store/store.env
    depends_on:
      - rabbitmq
      - store_db

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: docker/book_store/Dockerfile
    networks:
      - store_net
    volumes:
      - ./book_store/:/usr/app/
    command: celery -A book_store beat -l INFO
    env_file:
      - book_store/store.env
    depends_on:
      - celery_worker
      - store_db


  book_warehouse:
    container_name: book_warehouse
    build:
      context: .
      dockerfile: docker/book_warehouse/Dockerfile
    restart: "on-failure"
    volumes:
      - ./book_warehouse/:/usr/app/
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8001" ]
    networks:
      - nginx_net
      - warehouse_net
    env_file:
      - book_warehouse/warehouse.env
    expose:
      - "8001"
    depends_on:
      - warehouse_db

  warehouse_db:
    container_name: warehouse_db
    image: postgres:latest
    restart: "on-failure"
    networks:
      - warehouse_net
    volumes:
      - warehouse_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: warehouse_postgres
      POSTGRES_USER: warehouse_postgres

volumes:
  store_postgres:
  warehouse_postgres:
  book_store:
  book_warehouse:
  redis_data:
  rabbitmq_data:

networks:
  nginx_net:
  store_net:
  warehouse_net:

# sudo -u rabbitmq rabbitmqctl stop
# sudo systemctl stop nginx

# Successfully installed django-celery-beat-2.4.0 django-timezone-field-5.0 python-crontab-2.6.0 python-dateutil-2.8.2 tzdata-2022.6